### ISSUE TITLE
Please tell me how to use it.

### ISSUE THREAD

**Issue by bbbBBBSG** [ppoffice/dejavu#1]
Please tell me how to use it.

**Comment by ppoffice** [comment]
@bbbBBBSG 
1. Make sure your device is rooted or you can place the executables into a partition that allows execution.
2. Download the prebuilt executables (`record` and `replay`) from the `releases` or built them using Android NDK. Place the executables on your Android device (e.g., through `adb push`).
3. Start an `adb shell` and run the following command to start recording
    ```shell
    </path/to>/record </path/to>/recorded.txt
    ```
    Remember to substitute `</path/to>` with the actual location you put the executables and save the record files. For example

    ```shell
    /data/local/record /sdcard/recorded.txt
    ```
4. Interact with your device in the desired way. When finished, press `Ctrl+C` to end the recording.
5. Return to the same screen when you start the recording and run the following command to replay your recording
    ```shell
    </path/to>/replay </path/to>/recorded.txt
    ```
